name: Auto Assign to Project

on:
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign new issues
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: https://github.com/delphes99/pythie-bot/projects/1
          column_name: Proposition